### ISSUE TITLE
std::length_error (vector::_M_fill_insert) Error running large cohorts through DiaNN 1.8/1.8.1

### ISSUE THREAD

**Issue by MichaelDausmann** [vdemichev/DiaNN#725]
We are attempting to run large cohorts of files through DIA-NN. 

**Expected Behaviour**
diann execution completes without error yielding a speclib file

**Actual Behaviour**
Error Message
![diann_fail](https://github.com/vdemichev/DiaNN/assets/67457186/1072444f-d6de-40b8-a0f6-e5fa6ab63ab2)

**CommandLine**
```
/usr/diann/1.8/diann-1.8 --dir . --lib ../inputs/fasta-generated-srl.tsv.speclib --threads 32 --verbose 99 --window 9 --mass-acc-ms1 40 --pg-level 1 --mass-acc 40 --min-pr-charge 2 --max-pr-charge 4 --out step2-out.tsv --qvalue 0.01 --temp . --out-lib step2-lib.tsv --gen-spec-lib --predictor --min-fr-mz 100 --max-fr-mz 2000 --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 400 --max-pr-mz 1250 --unimod4 --smart-profiling --int-removal 1 --peak-center --use-quant
```
Note) in our execution scenario, the quant files already exist in the current folder (.) and from strace, we can see that all of the quant files have been read/loaded immediately prior to the exception.

**Behaviour and number of input files**
We have made several large runs to understand the limitation.
- 30k input files -> Fail
- 25k input files -> Success
- 20k input files -> Success

**Runtime Environment**
Linux Centos8 in a container (also tried windows with same behaviour).   diann 1.8 (also tried with 1.7.12 and 1.8.1 with same behaviour).

**Core Dump**
```
(gdb) bt
#0  0x00007fb03018637f in raise () from /lib64/libc.so.6
#1  0x00007fb030170db5 in abort () from /lib64/libc.so.6
#2  0x00007fb030b3e09b in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /lib64/libstdc++.so.6
#3  0x00007fb030b4453c in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#4  0x00007fb030b44597 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007fb030b447f8 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007fb030b40025 in std::__throw_length_error(char const*) [clone .cold.3] () from /lib64/libstdc++.so.6
#7  0x000055643b88706f in std::vector<int, std::allocator<int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, unsigned long, int const&) ()
#8  0x000055643b8c8e9e in Library::Info::load(Library*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<Quant, std::allocator<Quant> >*) ()
#9  0x000055643b82b0c1 in main ()
```

**Code Analysis**
By referencing the 1.7.12 source, it is apparent that the exception is raised from within the following function and is related to an operation on a vector.
```
void load(Library * parent, std::vector<std::string> &files, std::vector<Quant> * _quants = NULL) { // files currently must be the same as ms_files
```

Error Message
![diann_fail](https://github.com/vdemichev/DiaNN/assets/67457186/1072444f-d6de-40b8-a0f6-e5fa6ab63ab2)

**Comment by vdemichev** [comment]
Not sure what could go wrong here. 
Can it be lack of RAM in the system? What does RAM usage monitoring show?
Also, please follow the two-step pipeline of create .predicted.speclib -> analyse the files with it. Respectively, when aggregating the .quant files that have already been generated, the same .predicted.speclib needs to be provided.
Other comments: not sure for which instrument 40ppm mass acc is optimal?
Please also use 1.8.1, 1.8 has been known to produce some crashes on Linux.
