### ISSUE TITLE
Command line reference?

### ISSUE THREAD

**Issue by tobiasko** [vdemichev/DiaNN#83]
Dear DIA-NN developers,

I am currently testing DIA-NN on a Linux server and was wondering were to find a command line reference? The GitHub README showcases some basic commands, but it seems there is also a lot missing.

For instance, how would I command a library-free search incl. spectral and RT prediction (btw: is this a trained PROSIT model you are using here?)

Best,
Tobi

**Comment by vdemichev** [comment]
Hi Tobi,

The DIA-NN GUI under Windows works by launching the command line tool, diann.exe, with a set of commands which corresponds to user settings. I thus recommend to see what commands the GUI uses depending on the settings, and just replicate those on Linux. Also, the manual has some extra commands listed.

No, it's an in house prediction model with a number of advantages when compared to Prosit (e.g. peptide length is unlimited).

Best wishes,

Vadim

**Comment by tobiasko** [comment]
Hi Vadim,

thanks for your fast reply! So there is currently no command line reference available? Is there a GUI on Linux that can be used via `ssh -Y`? Having to install on a  MS windows server to figure out commands for the linux shell is a bit cumbersome.

Best,
Tobi

**Comment by vdemichev** [comment]
Hi Tobi, 

Yes, unfortunately need to install a Windows version of DIA-NN GUI somewhere.

Vadim

**Comment by tobiasko** [comment]
Hi there,

sorry to reopen this again, but I am constantly getting error messages when running the Windows GUI:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.WindowsAPICodePack.Taskbar.TabbedThumbnailNativeMethods.SetIconicThumbnail(IntPtr hwnd, IntPtr hBitmap)
   at Microsoft.WindowsAPICodePack.Taskbar.TaskbarWindowManager.DispatchMessage(Message& m, TaskbarWindow taskbarWindow)
   at Microsoft.WindowsAPICodePack.Taskbar.TabbedThumbnailProxyWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3750.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DIA-NN
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Software/DIA-NN/DIA-NN.exe
----------------------------------------
EasyTabs
    Assembly Version: 2.0.0.33
    Win32 Version: 2.0.0.33
    CodeBase: file:///D:/Software/DIA-NN/EasyTabs.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3701.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3650.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Win32Interop.User32
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///D:/Software/DIA-NN/Win32Interop.User32.DLL
----------------------------------------
Win32Interop.Uxtheme
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///D:/Software/DIA-NN/Win32Interop.Uxtheme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3630.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Software/DIA-NN/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Win32Interop.Dwmapi
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///D:/Software/DIA-NN/Win32Interop.Dwmapi.DLL
----------------------------------------
Svg
    Assembly Version: 2.4.3.29446
    Win32 Version: 2.4.3.29446
    CodeBase: file:///D:/Software/DIA-NN/Svg.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Software/DIA-NN/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3770.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Win32Interop.Kernel32
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///D:/Software/DIA-NN/Win32Interop.Kernel32.DLL
----------------------------------------
Win32Interop.Gdi32
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///D:/Software/DIA-NN/Win32Interop.Gdi32.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
Any idea how this could be solved?

**Comment by tobiasko** [comment]
I updated the .NET framework yesterday.

<img width="483" alt="Screenshot 2021-02-17 at 15 13 44" src="https://user-images.githubusercontent.com/12233339/108216541-e50bee80-7132-11eb-8721-5d63f3e7c000.png">

**Comment by tobiasko** [comment]
Is a specific version needed?

**Comment by vdemichev** [comment]
Some bug in the GUI, can just click "Continue"? I think the bug is caused by it incorrectly processing input in some fields (which on our machines happens rarely), restarting the GUI seems to fix it. If you wish, I can share the latest development version (please then contact me by email), haven't had these bugs with it.

**Comment by tobiasko** [comment]
ok. I will contact you by email.

**Comment by tobiasko** [comment]
Hi @vdemichev, did you get my email? I used the email shown in the DIA-NN GUI manual.
